# Generated by Django 3.0.5 on 2020-04-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200430_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
